baseURL= ""
languageCode= "en-us"
title= "Patrick's Angular Blog"
description= "Who wants pancakes!?"
author = "Patrick Armentrout"
paginate = 5
copyright = "All rights reserved - 2019"
theme = "startbootstrap-clean-blog"
disableKinds = ["tags", "in"]

[params]
  DateForm = "Mon, Jan 2, 2006"
  Description = "Who wants pancakes!?"
  Author = "Patrick Armentrout"
  email = "patrick.armentrout@gmail.com"
  Ganalytics = "UA-138628314-1"
  hjsStyle = "default"
  paginatedsections = ["posts"]

[[params.social]]
    title = "twitter"
    url = "https://twitter.com/patricka50"
[[params.social]]
    title = "github"
    url = "https://github.com/Parmentrout"